import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSelector } from "react-redux";



export default function Home() {
  const { Data} = useSelector((state) => state);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div>{Data.map(el => <p key={el.word}>{el.word}</p>)}</div>
      </main>
    </div>
  )
}
